import { expect, test, type Page } from '@playwright/test'

async function open(page: Page, slug: string) {
  page.on('pageerror', (error) => {
    throw error
  })
  await page.goto('#/learn/' + slug + '?mode=experiment')
  await expect(page.locator('.workbench')).toBeVisible()
}
function metric(page: Page, label: string) {
  return page
    .locator('.metric')
    .filter({ has: page.getByText(label, { exact: true }) })
    .locator('strong')
}
async function finish(page: Page, answer: RegExp) {
  await expect(page.locator('.experiment-goal')).toHaveClass(/reached/)
  await page.getByRole('tab', { name: /Challenge/ }).click()
  await page.getByRole('radio', { name: answer }).check()
  await page.getByRole('button', { name: '验证我的理解' }).click()
  await page.getByRole('button', { name: '完成本课', exact: true }).click()
  await expect(page.getByRole('button', { name: '已完成', exact: true })).toBeDisabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
}

test('database page pins prevent eviction while dirty inserts need writeback', async ({ page }) => {
  await open(page, 'database-pages')
  await page.getByRole('button', { name: '读取并 pin 当前页' }).click()
  await page.getByRole('button', { name: '读取数据库页', exact: true }).click()
  await expect(metric(page, '数据页读盘')).toHaveText('1')
  await expect(metric(page, 'Buffer Pool 命中')).toHaveText('1')
  await page.getByRole('button', { name: '回收当前缓冲页' }).click()
  await expect(page.locator('.experiment-feedback')).toContainText('仍被 pin')
  await page.getByRole('button', { name: '释放当前页的一次 pin' }).click()
  await page.getByRole('button', { name: '插入记录', exact: true }).click()
  await expect(metric(page, '脏页数量')).toHaveText('1')
  await expect(page.locator('[data-table="database-records"]')).toContainText('88')
  await page.getByRole('button', { name: '写回全部脏页' }).click()
  await expect(metric(page, '数据页写盘')).toHaveText('1')
  await expect(page.locator('[data-table="database-disk"]')).toContainText('10:88')
  await finish(page, /不能，仍有使用引用/)
})

test('WAL blocks an unsafe page flush then demonstrates committed redo and loser undo', async ({ page }) => {
  await open(page, 'wal')
  await page.getByRole('button', { name: 'BEGIN · 开始转账' }).click()
  await page.getByRole('button', { name: 'UPDATE · A 扣款' }).click()
  await page.getByRole('button', { name: '尝试刷写数据页' }).click()
  await expect(page.locator('.experiment-feedback')).toContainText('WAL 阻止写页')
  await page.getByRole('button', { name: 'UPDATE · B 入账' }).click()
  await page.getByRole('button', { name: 'COMMIT · 刷日志后确认' }).click()
  await expect(metric(page, '数据页写入次数')).toHaveText('0')
  await expect(metric(page, '已确认提交')).toHaveText('1')
  await page.getByRole('button', { name: '模拟数据库崩溃' }).click()
  await page.getByRole('button', { name: '根据持久日志恢复' }).click()
  await expect(metric(page, '本次 REDO')).toHaveText('2')
  await page.getByRole('button', { name: 'BEGIN · 开始转账' }).click()
  await page.getByRole('button', { name: 'UPDATE · A 扣款' }).click()
  await page.getByRole('button', { name: '仅持久化日志' }).click()
  await page.getByRole('button', { name: '尝试刷写数据页' }).click()
  await expect(metric(page, '磁盘账户总额')).toHaveText('190')
  await page.getByRole('button', { name: '模拟数据库崩溃' }).click()
  await page.getByRole('button', { name: '根据持久日志恢复' }).click()
  await expect(metric(page, '本次 UNDO')).toHaveText('1')
  await expect(metric(page, '磁盘账户总额')).toHaveText('200')
  await finish(page, /恢复时根据持久提交日志 REDO/)
})

test('RR snapshot reads and current locking reads see different committed versions', async ({ page }) => {
  await open(page, 'transactions')
  await page.getByRole('button', { name: 'BEGIN 当前会话' }).click()
  await page.getByRole('button', { name: 'SELECT · 普通读取' }).click()
  await expect(metric(page, '当前会话读取值')).toHaveText('10')
  await page.getByLabel('当前数据库会话').selectOption('T2')
  await page.getByRole('button', { name: 'BEGIN 当前会话' }).click()
  await page.getByRole('button', { name: 'UPDATE · 设置库存值' }).click()
  await page.getByRole('button', { name: 'COMMIT 当前会话' }).click()
  await page.getByLabel('当前数据库会话').selectOption('T1')
  await page.getByRole('button', { name: 'SELECT · 普通读取' }).click()
  await expect(metric(page, '当前会话读取值')).toHaveText('10')
  await page.getByRole('button', { name: 'SELECT FOR UPDATE · 当前读' }).click()
  await expect(metric(page, '当前会话读取值')).toHaveText('20')
  await page.getByRole('button', { name: 'COMMIT 当前会话' }).click()
  await page.getByRole('button', { name: '对比四种事务隔离规则' }).click()
  await expect(page.locator('[data-table="isolation-comparison"] tbody tr')).toHaveCount(4)
  await expect(page.locator('[data-table="isolation-comparison"] tbody tr').last()).toContainText('等待 T1')
  await finish(page, /普通读 10，当前锁定读 20/)
})

test('ANALYZE changes a poor stale estimate without changing query results', async ({ page }) => {
  await open(page, 'query-optimizer')
  await page.getByRole('button', { name: 'EXPLAIN · 查看估计' }).click()
  await expect(metric(page, '已返回行数')).toHaveText('0')
  await expect(metric(page, '估计结果行数')).toHaveText('1')
  await page.getByRole('button', { name: '运行优化器选择的路径' }).click()
  await expect(metric(page, '已返回行数')).toHaveText('18')
  await page.getByRole('button', { name: '实际执行两种访问路径' }).click()
  await expect(page.locator('[data-table="query-comparison"] tbody tr')).toHaveCount(2)
  await page.getByRole('button', { name: 'ANALYZE · 更新统计信息' }).click()
  await expect(metric(page, '估计结果行数')).toHaveText('18')
  await page.getByRole('button', { name: '运行优化器选择的路径' }).click()
  await expect(metric(page, '已返回行数')).toHaveText('18')
  await expect(page.locator('.experiment-feedback')).toContainText('全表扫描')
  await page.getByRole('button', { name: '实际执行两种访问路径' }).click()
  await finish(page, /成本估计偏离实际分布/)
})
