import { expect, test } from '@playwright/test'
import { click, fill, finishCourse, metric, openCourse, select } from './course-helpers'
test('CAP register compares minority rejection, local conflicts and eventual repair', async ({ page }) => {
  await openCourse(page, 'distributed-consistency')
  await click(page, '制造 A | B,C 网络分区')
  await click(page, '按当前协议执行写入')
  await expect(metric(page, '仲裁不足请求数')).toHaveText('1')
  await select(page, 'mode', 'local')
  await click(page, '制造 A | B,C 网络分区')
  await click(page, '按当前协议执行写入')
  await select(page, 'selected', 'B')
  await fill(page, 'value', '2')
  await click(page, '按当前协议执行写入')
  await click(page, '恢复网络通信')
  await click(page, '执行全组反熵修复')
  await expect(metric(page, '当前不同值数量')).toHaveText('1')
  await finishCourse(page, /系统能够按协议收敛/)
})
test('Raft rejects isolated leader commitment and repairs its uncommitted suffix after election', async ({
  page,
}) => {
  await openCourse(page, 'raft-consensus')
  const drain = () => click(page, '投递当前全部可达 RPC')
  await click(page, '触发当前节点选举超时')
  await drain()
  await click(page, 'Leader 追加业务提案')
  await drain()
  await select(page, 'isolated', 'A')
  await fill(page, 'value', '9')
  await click(page, 'Leader 追加业务提案')
  await drain()
  await expect(metric(page, '已提交业务提案数')).toHaveText('1')
  await select(page, 'selected', 'B')
  await click(page, '触发当前节点选举超时')
  await drain()
  await fill(page, 'value', '7')
  await click(page, 'Leader 追加业务提案')
  await drain()
  await select(page, 'isolated', 'none')
  await click(page, 'Leader 发送日志 / 心跳')
  await drain()
  await expect(metric(page, '已提交业务提案数')).toHaveText('2')
  await finishCourse(page, /保留已经提交的共同前缀/)
})
test('Fencing rejects the stale client after lease expiration and a newer resource write', async ({
  page,
}) => {
  await openCourse(page, 'distributed-locks')
  const scenario = async () => {
    await click(page, '申请带单调 token 的租约')
    await click(page, '暂停当前客户端')
    for (let i = 0; i < 3; i++) await click(page, '租约服务推进一秒')
    await select(page, 'selected', 'T2')
    await click(page, '申请带单调 token 的租约')
    await fill(page, 'value', '20')
    await click(page, '携带局部 token 写受保护资源')
    await select(page, 'selected', 'T1')
    await click(page, '恢复当前客户端')
    await fill(page, 'value', '99')
    await click(page, '携带局部 token 写受保护资源')
  }
  await scenario()
  await expect(metric(page, '资源最终值')).toHaveText('99')
  await select(page, 'mode', 'fenced')
  await scenario()
  await expect(metric(page, '资源最终值')).toHaveText('20')
  await finishCourse(page, /资源原子拒绝较旧 token/)
})
test('2PC recovers its durable commit while Saga retries compensation through an intermediate state', async ({
  page,
}) => {
  await openCourse(page, 'distributed-transactions')
  await click(page, '2PC 开始事务')
  await click(page, '当前参与者 prepare 并投票')
  await select(page, 'selected', 'B')
  await click(page, '当前参与者 prepare 并投票')
  await click(page, '协调者持久记录最终决定')
  await click(page, '停止协调者')
  await click(page, '当前参与者等待超时')
  await click(page, '恢复协调者并读取持久决定')
  await click(page, '向当前参与者重发最终决定')
  await select(page, 'selected', 'A')
  await click(page, '向当前参与者重发最终决定')
  await select(page, 'mode', 'saga')
  await select(page, 'rejectB', 'on')
  await click(page, '执行 Saga 下一步本地事务')
  await expect(metric(page, '当前已提交余额总和')).toHaveText('180')
  await click(page, '执行 Saga 下一步本地事务')
  await select(page, 'compensationDown', 'on')
  await click(page, '执行 / 重试幂等补偿')
  await select(page, 'compensationDown', 'off')
  await click(page, '执行 / 重试幂等补偿')
  await expect(metric(page, '当前已提交余额总和')).toHaveText('200')
  await finishCourse(page, /它可能处于不确定状态/)
})
test('Service resilience limits bursts and handles retries, circuit breaking and late idempotent effects', async ({
  page,
}) => {
  await openCourse(page, 'service-resilience')
  await click(page, '刷新客户端服务发现快照')
  await click(page, '同刻突发四个逻辑请求')
  await click(page, '运行到请求与迟到工作都结束')
  await expect(metric(page, '入口限流拒绝')).toHaveText('1')
  await expect(metric(page, '实际业务效果数')).toHaveText('3')
  await expect(metric(page, '迟到 / 重试去重次数')).toHaveText('2')
  await finishCourse(page, /超时只结束客户端等待/)
})
