import { expect, test } from '@playwright/test'
import { click, fill, finishCourse, metric, openCourse, select } from './course-helpers'
test('Spring container resolves candidates, caches singletons and delegates prototype destruction', async ({
  page,
}) => {
  await openCourse(page, 'spring-container')
  await click(page, '注册 BeanDefinition')
  await click(page, 'BeanFactory.getBean · 解析依赖')
  await expect(page.locator('.experiment-feedback')).toContainText('NoUniqueBeanDefinitionException')
  await select(page, 'qualifier', 'memoryRepo')
  await click(page, '注册 BeanDefinition')
  await click(page, 'ApplicationContext.refresh · 预实例化')
  await click(page, 'BeanFactory.getBean · 解析依赖')
  await click(page, 'BeanFactory.getBean · 解析依赖')
  await select(page, 'scope', 'prototype')
  await select(page, 'target', 'service')
  await click(page, '注册 BeanDefinition')
  await click(page, 'BeanFactory.getBean · 解析依赖')
  await click(page, 'BeanFactory.getBean · 解析依赖')
  await click(page, '关闭容器并销毁受管理单例')
  await finishCourse(page, /Controller 持有最初注入的 Service/)
})
test('Spring transaction proxy changes actual commit behavior across identical failures', async ({
  page,
}) => {
  await openCourse(page, 'spring-transactions')
  await select(page, 'path', 'self')
  await select(page, 'failure', 'runtime')
  await click(page, '运行当前转账到返回')
  await expect(metric(page, '已提交余额总和')).toHaveText('130')
  await click(page, '重开相同余额的转账')
  await select(page, 'path', 'proxy')
  await click(page, '运行当前转账到返回')
  await expect(metric(page, '已提交余额总和')).toHaveText('150')
  await click(page, '重开相同余额的转账')
  await select(page, 'failure', 'none')
  await click(page, '运行当前转账到返回')
  await expect(page.locator('[data-table="spring-tx-balances"]')).toContainText('70')
  await finishCourse(page, /共享事务可能已被标记 rollback-only/)
})
test('Spring MVC distinguishes binding failure, business errors and view rendering', async ({ page }) => {
  await openCourse(page, 'spring-mvc')
  const run = () => click(page, '处理请求直到 HTTP 返回')
  await run()
  await expect(metric(page, 'Controller 调用次数')).toHaveText('0')
  await expect(metric(page, '响应状态')).toHaveText('400')
  await fill(page, 'body', '{"quantity":3}')
  await run()
  await expect(metric(page, '响应状态')).toHaveText('201')
  await select(page, 'method', 'GET')
  await fill(page, 'url', '/orders/999')
  await run()
  await expect(metric(page, '响应状态')).toHaveText('404')
  await fill(page, 'url', '/hello?name=%3Cscript%3E')
  await select(page, 'accept', 'text/html')
  await run()
  await expect(page.locator('[data-table="mvc-response"]')).toContainText('&lt;script&gt;')
  await finishCourse(page, /参数解析阶段返回 400，Controller 没被调用/)
})
