import { expect, test, type Page } from '@playwright/test'

async function open(page: Page, slug: string) {
  page.on('pageerror', (error) => {
    throw error
  })
  await page.goto('#/learn/' + slug + '?mode=experiment')
  await expect(page.locator('.workbench')).toBeVisible()
}
function metric(page: Page, label: string) {
  return page
    .locator('.metric')
    .filter({ has: page.getByText(label, { exact: true }) })
    .locator('strong')
}
async function edit(page: Page, label: string, value: string) {
  await page.getByLabel(label, { exact: true }).fill(value)
  await page.getByLabel(label, { exact: true }).press('Tab')
}
async function finish(page: Page, answer: RegExp) {
  await expect(page.locator('.experiment-goal')).toHaveClass(/reached/)
  await page.getByRole('tab', { name: /Challenge/ }).click()
  await page.getByRole('radio', { name: answer }).check()
  await page.getByRole('button', { name: '验证我的理解' }).click()
  await page.getByRole('button', { name: '完成本课', exact: true }).click()
  await expect(page.getByRole('button', { name: '已完成', exact: true })).toBeDisabled()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
}

test('DMA preserves bus transfers while removing per-byte CPU copies', async ({ page }) => {
  await open(page, 'interrupt-dma')
  await page.getByRole('button', { name: '运行到数据与任务完成' }).click()
  await expect(metric(page, 'CPU 搬运字节')).toHaveText('6')
  await expect(metric(page, '后台任务完成')).toHaveText('12 / 12')
  await page.getByLabel('设备传输方式').selectOption('dma')
  await page.getByRole('button', { name: '运行到数据与任务完成' }).click()
  await expect(metric(page, 'CPU 搬运字节')).toHaveText('0')
  await expect(metric(page, '总线传输字节')).toHaveText('6')
  await expect(metric(page, '中断次数')).toHaveText('1')
  await page.getByRole('button', { name: '对比轮询、中断与 DMA' }).click()
  await expect(page.locator('[data-table="transfer-comparison"] tbody tr')).toHaveCount(3)
  await finish(page, /数据由 DMA 控制器搬运/)
})

test('an open file survives unlink and its blocks are reclaimed after close', async ({ page }) => {
  await open(page, 'filesystem')
  await page.getByRole('button', { name: 'open · 打开文件' }).click()
  await page.getByRole('button', { name: 'link · 创建硬链接' }).click()
  await expect(metric(page, '目录项数量')).toHaveText('2')
  await expect(metric(page, '存活 inode')).toHaveText('1')
  await page.getByRole('button', { name: 'unlink · 删除名称' }).click()
  await edit(page, '文件名', 'copy')
  await page.getByRole('button', { name: 'unlink · 删除名称' }).click()
  await expect(metric(page, '目录项数量')).toHaveText('0')
  await expect(metric(page, '已分配数据块')).toHaveText('2')
  await page.getByRole('button', { name: 'read · 从 FD 读取' }).click()
  await expect(metric(page, '最近读取内容')).toHaveText('ABCD')
  await page.getByRole('button', { name: 'close · 关闭 FD' }).click()
  await expect(metric(page, '已分配数据块')).toHaveText('0')
  await expect(metric(page, '存活 inode')).toHaveText('0')
  await finish(page, /名字无法再查到，但 FD 仍引用 inode/)
})

test('shared mappings, private COW and file sync expose different values', async ({ page }) => {
  await open(page, 'page-cache')
  await page.getByRole('button', { name: 'mmap · 建立或替换映射' }).click()
  await expect(metric(page, '磁盘读页')).toHaveText('0')
  await page.getByRole('button', { name: 'store · 修改映射页' }).click()
  await page.getByLabel('当前映射进程').selectOption('Q')
  await page.getByRole('button', { name: 'mmap · 建立或替换映射' }).click()
  await page.getByRole('button', { name: 'load · 读取映射页' }).click()
  await expect(metric(page, '最近读取值')).toHaveText('99')
  await expect(metric(page, '磁盘读页')).toHaveText('1')
  await expect(metric(page, '缺页处理次数')).toHaveText('2')
  await page.getByLabel('新映射方式').selectOption('private')
  await page.getByRole('button', { name: 'mmap · 建立或替换映射' }).click()
  await page.getByLabel('写入页值').fill('77')
  await page.getByRole('button', { name: 'store · 修改映射页' }).click()
  await page.getByRole('button', { name: 'load · 读取映射页' }).click()
  await expect(metric(page, '最近读取值')).toHaveText('77')
  await page.getByRole('button', { name: 'msync · 同步当前映射' }).click()
  await expect(metric(page, '磁盘写页')).toHaveText('0')
  await page.getByLabel('当前映射进程').selectOption('P')
  await page.getByRole('button', { name: 'load · 读取映射页' }).click()
  await expect(metric(page, '最近读取值')).toHaveText('99')
  await page.getByRole('button', { name: 'fsync · 同步文件脏页' }).click()
  await expect(metric(page, '磁盘写页')).toHaveText('1')
  await expect(page.locator('[data-table="page-cache-disk"] tbody tr').first()).toContainText('99')
  await finish(page, /共享内存中的修改已可见/)
})

test('ET partial reads leave bytes without a new event, while a blocked read stays on its FD', async ({
  page,
}) => {
  await open(page, 'io-multiplexing')
  await page.getByRole('button', { name: '模拟数据到达' }).click()
  await page.getByRole('button', { name: '检查一次就绪事件 / timeout=0' }).click()
  await page.getByRole('button', { name: '只调用一次 read' }).click()
  await expect(metric(page, '最近 read 返回')).toHaveText('ab')
  await page.getByRole('button', { name: '检查一次就绪事件 / timeout=0' }).click()
  await expect(page.locator('.experiment-feedback')).toContainText('缓冲仍有字节，但当前没有新通知')
  await page.getByRole('button', { name: '循环 read 直到 EAGAIN' }).click()
  await expect(metric(page, 'EAGAIN 次数')).toHaveText('1')
  await expect(page.locator('[data-table="io-buffers"] tbody tr').first()).toContainText('abcd')
  await page.getByRole('button', { name: '对比 select、poll 与 epoll' }).click()
  await finish(page, /继续非阻塞读取，直到 EAGAIN/)
  await page.getByRole('tab', { name: /Experiment/ }).click()
  await page.getByLabel('IO 与通知方式 / 修改会重置').selectOption('blocking')
  await page.getByRole('button', { name: '只调用一次 read' }).click()
  await page.getByLabel('外部数据到达 FD').selectOption('99')
  await page.getByRole('button', { name: '模拟数据到达' }).click()
  await expect(page.locator('.experiment-feedback')).toContainText('线程仍阻塞在 FD 3')
  await expect(page.getByRole('button', { name: '只调用一次 read' })).toBeDisabled()
  await page.getByLabel('外部数据到达 FD').selectOption('3')
  await page.getByRole('button', { name: '模拟数据到达' }).click()
  await expect(page.getByRole('button', { name: '只调用一次 read' })).toBeEnabled()
})

test('a routed payload changes link headers and stops when TTL expires', async ({ page }) => {
  await open(page, 'network-layers')
  await page.getByRole('button', { name: '运行到交付或失败' }).click()
  await expect(metric(page, '应用收到的载荷')).toHaveText('hello')
  await expect(metric(page, 'ARP 广播次数')).toHaveText('2')
  await expect(metric(page, '当前 IP TTL')).toHaveText('2')
  await expect(page.locator('[data-table="network-frames"] tbody tr')).toHaveCount(2)
  await page.getByRole('button', { name: '保留 ARP 缓存重新发送' }).click()
  await page.getByRole('button', { name: '运行到交付或失败' }).click()
  await expect(metric(page, 'ARP 广播次数')).toHaveText('0')
  await finish(page, /本地网关 R 的 IP/)
  await page.getByRole('tab', { name: /Experiment/ }).click()
  await page.getByLabel('初始 IP TTL').fill('1')
  await page.getByRole('button', { name: '运行到交付或失败' }).click()
  await expect(page.locator('.experiment-feedback')).toContainText('Time Exceeded')
  await expect(metric(page, '应用收到的载荷')).toHaveText('—')
})

test('TLS identity failure prevents delivery despite equal shared values', async ({ page }) => {
  await open(page, 'tls')
  await page.getByLabel('服务器证书情形').selectOption('wrong-host')
  await page.getByRole('button', { name: '运行握手并尝试交付' }).click()
  await expect(metric(page, '客户端共享值')).toHaveText('2')
  await expect(metric(page, '服务器共享值')).toHaveText('2')
  await expect(metric(page, '应用收到的文字')).toHaveText('未交付')
  await expect(page.locator('.experiment-feedback')).toContainText('证书身份验证失败')
  await page.getByLabel('服务器证书情形').selectOption('valid')
  await page.getByLabel('握手途中改动').selectOption('finished')
  await page.getByRole('button', { name: '运行握手并尝试交付' }).click()
  await expect(page.locator('.experiment-feedback')).toContainText('Finished 验证失败')
  await page.getByLabel('握手途中改动').selectOption('none')
  await page.getByRole('button', { name: '运行握手并尝试交付' }).click()
  await expect(metric(page, '应用收到的文字')).toHaveText('hello')
  await page.getByRole('button', { name: '对比四种证书的验证结果' }).click()
  await finish(page, /拒绝应用数据交付/)
})
