import { describe, expect, it } from 'vitest'
import { fileIoTransition, initialFileIo, presentFileIo } from '../../src/experiments/models/java-file-io'
import {
  initialSelector,
  presentSelector,
  selectorTransition,
} from '../../src/experiments/models/nio-selector'
import { initialReactor, presentReactor, reactorTransition } from '../../src/experiments/models/netty-reactor'

describe('Java file streams and persistence boundaries', () => {
  it('copies exact UTF-8 bytes with fewer buffered reads and recovers only forced output', () => {
    let s = initialFileIo()
    const act = (type: string, value?: string) => {
      s = fileIoTransition(s, { type, value })
    }
    act('copy')
    expect(s.copied).toEqual([...new TextEncoder().encode('A中🙂B\n')])
    expect(s.readCalls).toBe(4)
    expect(s.outputBuffer).toHaveLength(2)
    expect(s.pageCache).toHaveLength(8)
    act('compare')
    expect(s.comparison.map((c) => c.calls)).toEqual([11, 4])
    expect(s.comparison[0]!.bytes).toEqual(s.comparison[1]!.bytes)
    act('force')
    expect(s.disk).toHaveLength(8)
    act('flush')
    expect(s.disk).toHaveLength(8)
    act('force')
    act('crash')
    expect(s.disk).toEqual(s.source)
    expect(presentFileIo(s).goal.reached).toBe(true)
  })
  it('treats zero as a byte, EOF as -1 and close as resource release rather than force', () => {
    let s = initialFileIo()
    s = fileIoTransition(s, { type: 'text', value: '\0Z' })
    s = fileIoTransition(s, { type: 'open' })
    s = fileIoTransition(s, { type: 'copy' })
    expect(s.copied).toEqual([0, 90])
    expect(s.eof).toBe(true)
    s = fileIoTransition(s, { type: 'close' })
    expect(s.pageCache).toEqual([0, 90])
    expect(s.disk).toEqual([])
    expect(fileIoTransition(s, { type: 'read' }).error).toContain('关闭')
    s = fileIoTransition(s, { type: 'crash' })
    expect(s.pageCache).toEqual([])
  })
})
describe('Selector readiness, partial frames and short writes', () => {
  it('retains a partial length frame and selected keys, writes partly and removes OP_WRITE', () => {
    let s = initialSelector()
    const act = (type: string, value?: string) => {
      s = selectorTransition(s, { type, value })
    }
    act('register')
    act('arrive')
    act('select')
    act('select')
    expect(s.selectedKeys).toHaveLength(1)
    expect(s.sockets[0]!.kernel).toEqual([2, 65])
    act('remove')
    act('read')
    act('flip')
    act('decode')
    expect(s.sockets[0]!.frames).toEqual([])
    act('compact')
    expect(s.sockets[0]!.position).toBe(2)
    act('packet', '66')
    act('arrive')
    act('read')
    act('flip')
    act('decode')
    expect(s.sockets[0]!.frames).toEqual(['AB'])
    act('compact')
    expect(s.sockets[0]!.position).toBe(0)
    act('write-interest')
    act('select')
    act('write')
    expect(s.sockets[0]!.sent).toEqual([2, 65])
    act('write')
    expect(s.sockets[0]!.sent).toEqual([2, 65])
    act('drain')
    act('write')
    act('write-interest')
    expect(s.sockets[0]!.sent).toEqual([2, 65, 66])
    expect(presentSelector(s).goal.reached).toBe(true)
  })
  it('distinguishes no data, EOF, read mode and cancellation from removing selected keys', () => {
    let s = initialSelector()
    const act = (type: string, value?: string) => {
      s = selectorTransition(s, { type, value })
    }
    act('read')
    expect(s.sockets[0]!.eof).toBe(false)
    act('register')
    act('arrive')
    act('peer-close')
    act('select')
    act('remove')
    expect(s.sockets[0]!.registered).toBe(true)
    act('read')
    expect(s.sockets[0]!.eof).toBe(false)
    act('read')
    expect(s.sockets[0]!.eof).toBe(true)
    act('flip')
    act('read')
    expect(s.error).toContain('读模式')
    act('cancel')
    expect(s.sockets[0]!.registered).toBe(false)
    act('packet', '1,256')
    act('arrive')
    expect(s.error).toContain('0–255')
  })
})
describe('Netty pipeline scheduling, buffer ownership and application backpressure', () => {
  it('offloads slow work, lets another channel finish first and drains high/low watermarks', () => {
    let s = initialReactor()
    const act = (type: string, value?: string) => {
      s = reactorTransition(s, { type, value })
    }
    act('submit')
    act('selected', 'C2')
    act('text', 'ok')
    act('cost', '1')
    act('submit')
    act('run')
    expect(s.completed.map((j) => j.channel)).toEqual(['C2', 'C1'])
    expect(s.stallTicks).toBe(0)
    expect(s.buffers.map((b) => b.refs)).toEqual([0, 0])
    expect(s.channels[0]!.autoRead).toBe(false)
    act('flush-all')
    expect(s.channels[0]!.sent).toEqual([10, ...new TextEncoder().encode('ABCDEFGHIJ')])
    expect(presentReactor(s).goal.reached).toBe(true)
  })
  it('keeps EventLoop work serial, detects use after autoRelease, and pauses new inbound dispatch under backpressure', () => {
    let s = { ...initialReactor(), offload: false }
    s = reactorTransition(s, { type: 'submit' })
    s = reactorTransition(s, { type: 'selected', value: 'C2' })
    s = reactorTransition(s, { type: 'submit' })
    s = reactorTransition(s, { type: 'run' })
    expect(s.stallTicks).toBe(8)
    expect(s.completed.map((j) => j.channel)).toEqual(['C1', 'C2'])
    s = { ...initialReactor(), retain: false }
    s = reactorTransition(s, { type: 'submit' })
    s = reactorTransition(s, { type: 'run' })
    expect(s.invalidAccess).toBe(1)
    expect(s.completed).toEqual([])
    s = reactorTransition(initialReactor(), { type: 'submit' })
    s = reactorTransition(s, { type: 'run' })
    s = reactorTransition(s, { type: 'submit' })
    s = reactorTransition(s, { type: 'run' })
    expect(s.channels[0]!.incoming).toHaveLength(1)
    expect(s.completed).toHaveLength(1)
    s = reactorTransition(s, { type: 'flush-all' })
    s = reactorTransition(s, { type: 'run' })
    expect(s.completed).toHaveLength(2)
  })
})
