import { describe, it, expect } from 'vitest'
import { initialKafka, kafkaTransition, presentKafka } from '../../src/experiments/models/kafka-delivery'
import {
  initialRabbit,
  presentRabbit,
  rabbitTransition,
  topicMatches,
} from '../../src/experiments/models/rabbitmq-delivery'
describe('Kafka producer and consumer delivery boundaries', () => {
  it('deduplicates broker retries but exposes consumer duplicate effects, early-offset loss and transactional output scope', () => {
    let s = initialKafka()
    const act = (type: string, value?: string) => {
      s = kafkaTransition(s, { type, value })
    }
    act('send')
    act('retry')
    expect(s.logs[0]).toHaveLength(1)
    expect(s.dedup).toBe(1)
    act('fetch')
    act('process')
    act('crash')
    act('fetch')
    act('process')
    act('commit')
    expect(s.externalEffects).toHaveLength(2)
    expect(s.committed).toEqual([1, 0])
    act('mode', 'at-most')
    act('send')
    act('fetch')
    act('crash')
    act('fetch')
    expect(s.error).toContain('没有更多')
    expect(s.externalEffects).toEqual([])
    act('mode', 'transactional')
    act('send')
    act('fetch')
    act('process')
    expect(s.output[0]!.state).toBe('pending')
    act('crash')
    act('fetch')
    act('process')
    act('commit')
    expect(s.output.map((o) => o.state)).toEqual(['aborted', 'committed'])
    expect(s.externalEffects).toHaveLength(2)
    expect(presentKafka(s).goal.reached).toBe(true)
  })
  it('resets assignment positions at committed offsets and rejects stale generations while preserving immutable fetch data', () => {
    let s = initialKafka()
    const act = (type: string, value?: string) => {
      s = kafkaTransition(s, { type, value })
    }
    act('key', 'A')
    act('send')
    act('partition', '1')
    act('fetch')
    act('value', '8')
    expect(s.consumers[0]!.pending!.value).toBe(1)
    act('process')
    act('rebalance')
    expect(s.assignment).toEqual(['C1', 'C2'])
    act('commit')
    expect(s.error).toContain('generation')
    act('selected', 'C2')
    act('fetch')
    expect(s.consumers[1]!.pending!.offset).toBe(0)
    act('process')
    act('commit')
    expect(s.committed[1]).toBe(1)
    act('idempotent', 'off')
    act('send')
    act('retry')
    expect(s.logs.flat()).toHaveLength(2)
  })
})
describe('RabbitMQ exchange routing, acknowledgments and inbox transactions', () => {
  it('routes copies, separates publisher confirmation from processing and survives unacked redelivery through an inbox', () => {
    let s = initialRabbit()
    const act = (type: string, value?: string) => {
      s = rabbitTransition(s, { type, value })
    }
    act('publish')
    expect(s.queues.map((q) => q.ready.length)).toEqual([1, 1, 0])
    act('confirm')
    expect(s.effects).toEqual([])
    act('deliver')
    act('deliver')
    expect(s.error).toContain('prefetch')
    act('process')
    act('disconnect')
    act('deliver')
    act('process')
    act('ack')
    expect(s.effects).toHaveLength(1)
    expect(s.skips).toBe(1)
    expect(s.unacked).toEqual([])
    act('routing', 'unmatched.created')
    act('publish')
    expect(s.publications.at(-1)!.returned).toBe(true)
    act('confirm')
    expect(s.publications.at(-1)!.confirmed).toBe(true)
    expect(presentRabbit(s).goal.reached).toBe(true)
  })
  it('allows at-most-once early ack, repeats effects without inbox and moves rejected messages to the configured DLX', () => {
    let s = { ...initialRabbit(), dedup: false }
    const act = (type: string) => {
      s = rabbitTransition(s, { type })
    }
    act('publish')
    act('deliver')
    act('process')
    act('disconnect')
    act('deliver')
    act('process')
    expect(s.effects).toHaveLength(2)
    act('nack-dead')
    expect(s.queues[2]!.ready).toHaveLength(1)
    s = initialRabbit()
    act('publish')
    act('deliver')
    act('ack')
    act('disconnect')
    expect(s.queues[0]!.ready).toEqual([])
    expect(s.effects).toEqual([])
  })
  it('implements topic segment wildcards rather than arbitrary substring matching', () => {
    expect(topicMatches('orders.*', 'orders.created')).toBe(true)
    expect(topicMatches('orders.*', 'orders.eu.created')).toBe(false)
    expect(topicMatches('orders.#', 'orders')).toBe(true)
    expect(topicMatches('orders.#', 'orders.eu.created')).toBe(true)
    expect(topicMatches('#.created', 'orders.eu.created')).toBe(true)
    expect(topicMatches('order.*', 'orders.created')).toBe(false)
  })
})
